version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins-local
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - test-net
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    restart: unless-stopped
    ports:
      - "4444:4444"
    command:
      - "-container-network"
      - "test-net"
      - "-limit"
      - "4"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./selenoid-config:/etc/selenoid:ro
    networks:
      - test-net

networks:
  test-net:
    name: test-net
volumes:
  jenkins_home:
